import { SiteConfig } from '../types';

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  name: 'CK',
  tagline: 'Trading × AI ×\nSystems × Experiments',
  taglineZh: '交易 × AI ×\n系統 × 實驗',
  bio: 'I build tools, systems and experiments around trading, AI and decision-making.',
  bioZh: '我專注打造與交易、AI 和決策有關的工具、系統與實驗。',
  email: 'hello@example.com',
  github: 'https://github.com/',
  tradingView: 'https://www.tradingview.com/',
  contactLinks: [
    { id: 'github', label: 'GitHub', labelZh: 'GitHub', url: 'https://github.com/' },
    { id: 'tradingview', label: 'TradingView', labelZh: 'TradingView', url: 'https://www.tradingview.com/' },
  ],
  availability: 'Open to focused collaborations and ambitious prototypes.',
  availabilityZh: '目前開放目標明確的合作與具企圖心的原型專案。',
  contactEyebrow: "LET'S TALK", contactEyebrowZh: '聊聊你的想法',
  contactTitle: 'Have a project, problem or idea?', contactTitleZh: '有專案、問題或想法嗎？',
  contactBody: "If you have a project, collaboration, TradingView indicator, AI tool, automation, website or another idea, leave the context here. I'll review it and suggest a practical way forward.",
  contactBodyZh: '如果你有專案、合作、TradingView 指標、AI 工具、自動化、網站或其他想法，歡迎留下需求。我會閱讀內容，並提出實際可行的合作方式。',
  projectTypeOptions: [
    { id: 'indicator', label: 'TradingView / Pine Script Indicator', labelZh: 'TradingView／Pine Script 指標' },
    { id: 'quant', label: 'Trading / Quant Tool', labelZh: '交易／量化工具' },
    { id: 'ai', label: 'AI / Agent / Automation', labelZh: 'AI／Agent／自動化' },
    { id: 'website', label: 'Website / Web App', labelZh: '網站／Web App' },
    { id: 'dashboard', label: 'Dashboard / Data Tool', labelZh: '儀表板／資料工具' },
    { id: 'prototype', label: 'Prototype / MVP', labelZh: 'Prototype／MVP' },
    { id: 'collaboration', label: 'Collaboration', labelZh: '合作' },
    { id: 'other', label: 'Other', labelZh: '其他' },
  ],
  budgetOptions: [
    { id: 'under-10k', label: 'Under NT$10,000', labelZh: 'NT$10,000 以下' },
    { id: '10k-30k', label: 'NT$10,000 – 30,000', labelZh: 'NT$10,000－30,000' },
    { id: '30k-60k', label: 'NT$30,000 – 60,000', labelZh: 'NT$30,000－60,000' },
    { id: '60k-100k', label: 'NT$60,000 – 100,000', labelZh: 'NT$60,000－100,000' },
    { id: 'over-100k', label: 'NT$100,000+', labelZh: 'NT$100,000 以上' },
    { id: 'discuss', label: "Let's discuss", labelZh: '再討論' },
  ],
  timelineOptions: [
    { id: 'asap', label: 'ASAP', labelZh: '儘快' },
    { id: 'month', label: 'Within 1 month', labelZh: '一個月內' },
    { id: '1-3-months', label: '1–3 months', labelZh: '一至三個月' },
    { id: '3-plus-months', label: '3+ months', labelZh: '三個月以上' },
    { id: 'flexible', label: 'Flexible', labelZh: '時間彈性' },
  ],
  showHeader: true,
  showHero: true,
  showAbout: true,
  showFinalCta: true,
  navHome: 'Home', navHomeZh: '首頁',
  navProjects: 'Projects', navProjectsZh: '作品',
  navGallery: 'Certificates / Gallery', navGalleryZh: '證照／相簿',
  navContact: 'Contact', navContactZh: '聯絡',
  navCta: 'Work With Me', navCtaZh: '與我合作',
  heroEyebrow: 'INDEPENDENT BUILDER', heroEyebrowZh: '獨立創作者',
  heroPrimaryLabel: 'View My Work', heroPrimaryLabelZh: '瀏覽作品',
  heroSecondaryLabel: 'Work With Me', heroSecondaryLabelZh: '與我合作',
  aboutEyebrow: 'ABOUT', aboutEyebrowZh: '關於我',
  aboutTitle: 'I turn curiosity into useful systems.', aboutTitleZh: '把好奇心轉化成真正有用的系統。',
  aboutBody: 'Part trader, part builder, always experimenting. My work sits between quantitative research, AI-native workflows and rapid product prototyping.',
  aboutBodyZh: '我是交易者，也是創作者，持續透過實驗學習。我的工作橫跨量化研究、AI 原生工作流程與快速產品原型。',
  aboutTags: 'Trader\nBuilder\nAI-native Experimenter\nSystem Thinker\nRapid Prototyper\nQuant / Trading Research',
  aboutTagsZh: '交易者\n創作者\nAI 原生實驗者\n系統思考者\n快速原型實作者\n量化／交易研究',
  ctaEyebrow: 'HAVE AN IDEA?', ctaEyebrowZh: '有想法嗎？',
  ctaTitle: "Let's make it concrete.", ctaTitleZh: '一起把想法做成作品。',
  ctaBody: 'TradingView indicator · Trading / Quant tool · AI agent · Automation · Website · Dashboard · Prototype',
  ctaBodyZh: 'TradingView 指標 · 交易／量化工具 · AI Agent · 自動化 · 網站 · 儀表板 · 產品原型',
  ctaButtonLabel: 'Discuss a Project', ctaButtonLabelZh: '討論專案',
};
