import { SiteConfig } from '../types';

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  name: 'CK',
  tagline: 'Trading × AI ×\nSystems × Experiments',
  taglineZh: '交易 × AI ×\n系統 × 實驗',
  bio: 'I build tools, systems and experiments around trading, AI and decision-making.',
  bioZh: '我專注打造與交易、AI 和決策有關的工具、系統與實驗。',
  email: 'hello@example.com',
  github: 'https://github.com/',
  tradingView: 'https://www.tradingview.com/',
  availability: 'Open to focused collaborations and ambitious prototypes.',
  availabilityZh: '目前開放目標明確的合作與具企圖心的原型專案。',
  showHeader: true,
  showHero: true,
  showAbout: true,
  showFinalCta: true,
  navHome: 'Home', navHomeZh: '首頁',
  navProjects: 'Projects', navProjectsZh: '作品',
  navGallery: 'Certificates / Gallery', navGalleryZh: '證照／相簿',
  navContact: 'Contact', navContactZh: '聯絡',
  navCta: 'Work With Me', navCtaZh: '與我合作',
  heroEyebrow: 'INDEPENDENT BUILDER', heroEyebrowZh: '獨立創作者',
  heroPrimaryLabel: 'View My Work', heroPrimaryLabelZh: '瀏覽作品',
  heroSecondaryLabel: 'Work With Me', heroSecondaryLabelZh: '與我合作',
  aboutEyebrow: 'ABOUT', aboutEyebrowZh: '關於我',
  aboutTitle: 'I turn curiosity into useful systems.', aboutTitleZh: '把好奇心轉化成真正有用的系統。',
  aboutBody: 'Part trader, part builder, always experimenting. My work sits between quantitative research, AI-native workflows and rapid product prototyping.',
  aboutBodyZh: '我是交易者，也是創作者，持續透過實驗學習。我的工作橫跨量化研究、AI 原生工作流程與快速產品原型。',
  aboutTags: 'Trader\nBuilder\nAI-native Experimenter\nSystem Thinker\nRapid Prototyper\nQuant / Trading Research',
  aboutTagsZh: '交易者\n創作者\nAI 原生實驗者\n系統思考者\n快速原型實作者\n量化／交易研究',
  ctaEyebrow: 'HAVE AN IDEA?', ctaEyebrowZh: '有想法嗎？',
  ctaTitle: "Let's make it concrete.", ctaTitleZh: '一起把想法做成作品。',
  ctaBody: 'TradingView indicator · Trading / Quant tool · AI agent · Automation · Website · Dashboard · Prototype',
  ctaBodyZh: 'TradingView 指標 · 交易／量化工具 · AI Agent · 自動化 · 網站 · 儀表板 · 產品原型',
  ctaButtonLabel: 'Discuss a Project', ctaButtonLabelZh: '討論專案',
};
