export type ProjectStatus = string;
export interface ProjectItem { id: string; slug?: string; title: string; titleZh?: string; coverImage: string; shortDescription: string; shortDescriptionZh?: string; detailedDescription: string; detailedDescriptionZh?: string; category: string; categoryZh?: string; tags: string[]; year: number; status: ProjectStatus; statusZh?: string; externalUrl?: string; githubUrl?: string; demoUrl?: string; isFeatured: boolean; isPublic: boolean; displayOrder: number; createdAt: string; updatedAt: string; }
export type ViewMode = 'showcase' | 'management' | 'inquiries';
export type SortField = 'displayOrder' | 'year' | 'title' | 'updatedAt';
export type SortDirection = 'asc' | 'desc';
export type InquiryStatus = 'NEW' | 'CONTACTED' | 'QUOTED' | 'ACCEPTED' | 'CLOSED' | 'ARCHIVED';
export interface InquiryItem { id: string; date: string; clientName: string; clientEmail?: string; clientPhone?: string; projectName: string; projectType?: string; budgetRange: string; desiredTimeline?: string; referenceUrl?: string; sourceProjectId?: string; sourceProjectTitle?: string; status: InquiryStatus; requirements: string; contactMethod?: string; internalNotes?: string; additionalNotes?: string; createdAt: string; updatedAt: string; }
export interface SiteConfig { name: string; tagline: string; taglineZh?: string; bio: string; bioZh?: string; email: string; github?: string; tradingView?: string; linkedIn?: string; discord?: string; instagram?: string; x?: string; availability: string; availabilityZh?: string; }
export interface GalleryItem { id: string; title: string; titleZh?: string; description?: string; descriptionZh?: string; category: string; categoryZh?: string; year?: number; objectKey: string; imageUrl: string; mimeType: string; originalName: string; isPublic: boolean; isFeatured: boolean; displayOrder: number; createdAt: string; updatedAt: string; }
